version: "3.8"
services:
  mysql_db_container:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3308:3306"
    volumes:
      - mysql_db_data_container:/var/lib/mysql

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8082:8080

volumes:
  mysql_db_data_container:
